platform :ios, '15.0'
use_frameworks!

target 'GodotxRevenueCat' do
  pod 'RevenueCat', '5.47.1'
  pod 'RevenueCatUI', '5.47.1'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '15.0'
      config.build_settings['BUILD_LIBRARY_FOR_DISTRIBUTION'] = 'YES'
    end
  end
end

